name .NET Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on:ubuntu-latest

    steps:
      -uses: actions/checkout@v4

      -name: Setup .NET
      with:
        dotnet-version 8.0.X
      
      -name: Restore dependencies
      run: dotnet Restore

      -name Build
      run: dotnet build --no-restore --cofiguration Release

      -name Test
      run:dotnet test --no-build --verbosity normal

